"use client";

import { useState } from 'react';
import { Calculator, ArrowLeft, Download, FileText, Share2 } from 'lucide-react';
import Link from 'next/link';
import { jsPDF } from 'jspdf';

export default function CalculatorPage() {
  // State Input
  const [volume, setVolume] = useState<number | ''>('');
  const [ratio, setRatio] = useState('1:2:3'); 
  
  // State Hasil
  const [result, setResult] = useState<null | { 
    semen: number, 
    pasir: number, 
    kerikil: number,
    estimasiBiaya: number 
  }>(null);

  // HARGA ASUMSI (Bisa diupdate nanti via database)
  const HARGA = {
    semen: 65000, // per sak
    pasir: 250000, // per m3
    kerikil: 280000 // per m3
  };

  const calculateMaterial = () => {
    const vol = Number(volume);
    if (!vol) return;

    // Koefisien SNI (Estimasi)
    let semenCoef = 8.15; 
    let pasirCoef = 0.54; 
    let kerikilCoef = 0.82; 

    if (ratio === '1:3:5') {
        semenCoef = 6.5; 
        pasirCoef = 0.58; 
        kerikilCoef = 0.85;
    }

    const hitungSemen = Math.ceil(vol * semenCoef);
    const hitungPasir = Number((vol * pasirCoef).toFixed(2));
    const hitungKerikil = Number((vol * kerikilCoef).toFixed(2));

    const totalBiaya = 
      (hitungSemen * HARGA.semen) + 
      (hitungPasir * HARGA.pasir) + 
      (hitungKerikil * HARGA.kerikil);

    setResult({
      semen: hitungSemen,
      pasir: hitungPasir,
      kerikil: hitungKerikil,
      estimasiBiaya: totalBiaya
    });
  };

  // --- FUNGSI SAKTI: GENERATE PDF ---
  const downloadPDF = () => {
    if (!result) return;
    
    const doc = new jsPDF();
    const vol = volume?.toString() || '0';

    // 1. KOP SURAT
    doc.setFontSize(22);
    doc.setTextColor(234, 88, 12); // Warna Orange (RGB)
    doc.text("CONTECH LABS", 20, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text("Digital Construction Solutions", 20, 25);
    doc.text("https://contech-portfolio.vercel.app", 20, 30);
    
    // Garis Pembatas
    doc.setLineWidth(0.5);
    doc.line(20, 35, 190, 35);

    // 2. JUDUL DOKUMEN
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("ESTIMASI MATERIAL BETON (RAB)", 20, 50);

    doc.setFontSize(10);
    doc.text(`Tanggal Cetak: ${new Date().toLocaleDateString('id-ID')}`, 20, 58);

    // 3. DETAIL INPUT
    doc.setFillColor(245, 245, 245);
    doc.rect(20, 65, 170, 25, 'F'); // Kotak abu-abu
    doc.text(`Volume Pengecoran: ${vol} m³`, 25, 75);
    doc.text(`Mutu / Rasio: ${ratio === '1:2:3' ? 'K-225 (Struktural)' : 'K-175 (Lantai Kerja)'}`, 25, 82);

    // 4. TABEL HASIL
    let y = 110;
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Rincian Kebutuhan:", 20, 100);

    // Header Tabel
    doc.setFontSize(10);
    doc.text("Material", 20, y);
    doc.text("Volume/Qty", 80, y);
    doc.text("Estimasi Harga", 140, y);
    doc.line(20, y+2, 190, y+2);
    
    // Isi Tabel
    y += 10;
    doc.setFont("helvetica", "normal");
    
    // Semen
    doc.text("Semen (40kg)", 20, y);
    doc.text(`${result.semen} Sak`, 80, y);
    doc.text(`Rp ${(result.semen * HARGA.semen).toLocaleString('id-ID')}`, 140, y);
    
    // Pasir
    y += 10;
    doc.text("Pasir Beton", 20, y);
    doc.text(`${result.pasir} m³`, 80, y);
    doc.text(`Rp ${(result.pasir * HARGA.pasir).toLocaleString('id-ID')}`, 140, y);

    // Kerikil
    y += 10;
    doc.text("Kerikil / Split", 20, y);
    doc.text(`${result.kerikil} m³`, 80, y);
    doc.text(`Rp ${(result.kerikil * HARGA.kerikil).toLocaleString('id-ID')}`, 140, y);

    // Total
    y += 15;
    doc.setLineWidth(0.5);
    doc.line(20, y-5, 190, y-5);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("ESTIMASI TOTAL BIAYA", 20, y);
    doc.setTextColor(234, 88, 12); // Orange
    doc.text(`Rp ${result.estimasiBiaya.toLocaleString('id-ID')}`, 140, y);

    // Footer Disclaimer
    doc.setTextColor(150);
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text("* Harga hanya estimasi kasar. Sesuaikan dengan harga toko lokal.", 20, 280);
    doc.text("Generated by ConTech Labs System", 140, 280);

    // Simpan File
    doc.save(`RAB-Beton-${vol}m3.pdf`);
  };

  return (
    <main className="min-h-screen bg-slate-50 p-4 font-sans flex items-center justify-center">
      <div className="w-full max-w-lg bg-white rounded-2xl shadow-xl border border-slate-200 overflow-hidden">
        
        {/* Header App */}
        <div className="bg-slate-900 p-6 text-white relative overflow-hidden">
           <div className="absolute top-0 right-0 -mr-10 -mt-10 w-32 h-32 bg-orange-600 rounded-full blur-2xl opacity-50"></div>
          <Link href="/" className="inline-flex items-center text-slate-300 hover:text-white mb-6 text-xs font-bold uppercase tracking-wider transition-colors relative z-10">
            <ArrowLeft className="w-4 h-4 mr-1" /> Kembali ke Dashboard
          </Link>
          <div className="flex items-center gap-4 relative z-10">
            <div className="p-3 bg-orange-600 rounded-xl shadow-lg shadow-orange-900/20">
              <Calculator className="w-8 h-8 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold">BetonCalc Pro</h1>
              <p className="text-slate-400 text-sm">AI-Powered Estimator & RAB Generator</p>
            </div>
          </div>
        </div>

        {/* Form Input */}
        <div className="p-8 space-y-6">
          <div>
            <label className="block text-sm font-bold text-slate-700 mb-2">Volume Cor (m³)</label>
            <div className="relative">
                <input 
                type="number" 
                value={volume}
                onChange={(e) => setVolume(Number(e.target.value))}
                placeholder="0"
                className="w-full p-4 pl-4 border border-slate-200 bg-slate-50 rounded-xl focus:ring-2 focus:ring-orange-500 focus:border-orange-500 outline-none transition-all font-mono text-2xl font-bold text-slate-900 placeholder:text-slate-300"
                />
                <span className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 font-bold">m³</span>
            </div>
          </div>

          <div>
            <label className="block text-sm font-bold text-slate-700 mb-2">Mutu / Rasio Campuran</label>
            <select 
              value={ratio}
              onChange={(e) => setRatio(e.target.value)}
              className="w-full p-4 border border-slate-200 rounded-xl focus:ring-2 focus:ring-orange-500 outline-none bg-white text-slate-700 appearance-none font-medium"
            >
              <option value="1:2:3">K-225 (Standar Struktur 1:2:3)</option>
              <option value="1:3:5">K-175 (Cor Lantai Kerja 1:3:5)</option>
            </select>
          </div>

          <button 
            onClick={calculateMaterial}
            className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-4 rounded-xl transition-all shadow-lg hover:shadow-xl active:scale-95 flex items-center justify-center gap-2"
          >
            <Calculator className="w-5 h-5" />
            HITUNG KEBUTUHAN
          </button>
        </div>

        {/* Hasil Perhitungan */}
        {result && (
          <div className="bg-slate-50 p-6 border-t border-slate-200 animate-in slide-in-from-bottom-4 duration-500">
            <div className="flex items-center justify-between mb-6">
                <h3 className="text-slate-900 font-bold flex items-center gap-2">
                    <FileText className="w-5 h-5 text-orange-600" />
                    Hasil Estimasi
                </h3>
                <span className="text-xs bg-green-100 text-green-700 px-2 py-1 rounded font-bold">READY TO PRINT</span>
            </div>
            
            <div className="grid grid-cols-3 gap-3 text-center mb-6">
              <div className="bg-white p-3 rounded-lg border border-slate-200 shadow-sm">
                <div className="text-xl font-bold text-slate-900 mb-1">{result.semen}</div>
                <div className="text-[10px] text-slate-500 font-bold uppercase">Sak Semen</div>
              </div>
              <div className="bg-white p-3 rounded-lg border border-slate-200 shadow-sm">
                <div className="text-xl font-bold text-orange-600 mb-1">{result.pasir}</div>
                <div className="text-[10px] text-slate-500 font-bold uppercase">Pasir (m³)</div>
              </div>
              <div className="bg-white p-3 rounded-lg border border-slate-200 shadow-sm">
                <div className="text-xl font-bold text-slate-900 mb-1">{result.kerikil}</div>
                <div className="text-[10px] text-slate-500 font-bold uppercase">Kerikil (m³)</div>
              </div>
            </div>

            <div className="bg-orange-50 border border-orange-100 p-4 rounded-xl flex justify-between items-center mb-6">
                <span className="text-sm text-orange-800 font-medium">Estimasi Biaya</span>
                <span className="text-lg font-bold text-orange-700">Rp {result.estimasiBiaya.toLocaleString('id-ID')}</span>
            </div>
            
            <div className="grid grid-cols-2 gap-3">
                 <button 
                    onClick={() => alert('Fitur Share WhatsApp akan aktif di versi Pro')}
                    className="flex items-center justify-center gap-2 text-sm font-bold text-slate-600 hover:text-slate-900 py-3 border border-slate-300 rounded-xl hover:bg-slate-100 transition-colors"
                 >
                    <Share2 className="w-4 h-4" /> Share
                 </button>
                 <button 
                    onClick={downloadPDF}
                    className="flex items-center justify-center gap-2 text-sm font-bold text-white bg-orange-600 hover:bg-orange-700 py-3 rounded-xl shadow-lg shadow-orange-200 active:scale-95 transition-all"
                 >
                    <Download className="w-4 h-4" /> Download PDF
                 </button>
            </div>
          </div>
        )}
      </div>
    </main>
  );
}